### ISSUE TITLE
pysnmp.smi.error.MibNotFoundError: IF-MIB compilation error(s): missingcaused....

### ISSUE THREAD

**Issue by bbrendon** [zerxen/SnmpNetworkTopologyVisualizator#1]
Any idea what went wrong?

```
root@hostname:/opt/SnmpNetworkTopologyVisualizator# python3 network_mapper.py
2019 Nov 23-22:12:57: ############
2019 Nov 23-22:12:57: # Starting #
2019 Nov 23-22:12:57: ############
2019 Nov 23-22:12:57: Initializing NetworkTopology class

############################################
Testing access to 10.1.1.1        ... 2019 Nov 23-22:12:57: Testing access to 10.1.1.1
DEBUG: len of result from fetch() 1
2019 Nov 23-22:12:57: SNMPv2-MIB::sysName.0 = sw-core
2019 Nov 23-22:12:57:  This is how to get to numeric OID: (1, 3, 6, 1, 2, 1, 1, 5, 0)
2019 Nov 23-22:12:57:  This is how to get data only: sw-core
2019 Nov 23-22:12:57: # Connection worked, will retrieve data next
2019 Nov 23-22:12:57: INTERFACES TABLE:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 368, in loadModules
    self.loadModule(modName, **userCtx)
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 348, in loadModule
    modName and modName + ".py[co]", ', '.join([str(x) for x in self.__mibSources]))
pysnmp.smi.error.MibNotFoundError: MIB file "IF-MIB.py[co]" not found in search path (DirMibSource('/usr/lib/python3/dist-packages/pysnmp/smi/mibs'), DirMibSource('/usr/lib/python3/dist-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('.'), DirMibSource('/root/.pysnmp/mibs'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "network_mapper.py", line 257, in <module>
    return_code = args.func(args)
  File "network_mapper.py", line 66, in main_with_args
    hlapi.CommunityData(config['DEFAULT']['SnmpCommunityString']))
  File "/opt/SnmpNetworkTopologyVisualizator/quicksnmp.py", line 63, in get_table
    return cut_array_to_table(fetch(handler),len(oids))
  File "/opt/SnmpNetworkTopologyVisualizator/quicksnmp.py", line 112, in fetch
    varBinds) in handler:
  File "/usr/lib/python3/dist-packages/pysnmp/hlapi/asyncore/sync/cmdgen.py", line 349, in nextCmd
    initialVars = [x[0] for x in vbProcessor.makeVarBinds(snmpEngine, varBinds)]
  File "/usr/lib/python3/dist-packages/pysnmp/hlapi/varbinds.py", line 39, in makeVarBinds
    __varBinds.append(varBind.resolveWithMib(mibViewController))
  File "/usr/lib/python3/dist-packages/pysnmp/smi/rfc1902.py", line 847, in resolveWithMib
    self.__args[0].resolveWithMib(mibViewController)
  File "/usr/lib/python3/dist-packages/pysnmp/smi/rfc1902.py", line 481, in resolveWithMib
    self.__modName, self.__symName
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 406, in importSymbols
    self.loadModules(modName, **userCtx)
  File "/usr/lib/python3/dist-packages/pysnmp/smi/builder.py", line 376, in loadModules
    raise error.MibNotFoundError('%s compilation error(s): %s' % (modName, errs))
pysnmp.smi.error.MibNotFoundError: IF-MIB compilation error(s): missingcaused by <class 'pysnmp.smi.error.MibNotFoundError'>: MIB file "IF-MIB.py[co]" not found in search path (DirMibSource('/usr/lib/python3/dist-packages/pysnmp/smi/mibs'), DirMibSource('/usr/lib/python3/dist-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('.'), DirMibSource('/root/.pysnmp/mibs'))
root@hostname:/opt/SnmpNetworkTopologyVisualizator# 
```

**Comment by MheniMerz** [comment]
Hi I'm having the same issue, was this problem resolved ?
thanks.

**Comment by zerxen** [comment]
Guys, this is simply you missing some MIBs , use $ pip install pysnmp-mibs

**Comment by MheniMerz** [comment]
i can confirm this worked for me,
thanks for the quick reply

**Comment by kvdinar** [comment]
I uninstalled the pysnmp, pysmi. After that installed pysnmp-mibs.
It worked fine.
